openapi: 3.0.0
info:
  title: "Direcciones - Gaucho Buy"
  description: "Endpoint para registrar direcciones de usuarios"
  version: "1.0.0"

paths:
  /api/direccion:
    post:
      summary: "Agregar nueva direcci칩n"
      description: "Crea una nueva direcci칩n asociada a un usuario"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/DireccionInput"
      responses:
        201:
          description: "Direcci칩n registrada exitosamente"
        400:
          description: "Datos inv치lidos"

components:
  schemas:
    DireccionInput:
      type: object
      properties:
        calle:
          type: string
        numero:
          type: string
        localidad:
          type: string
          description: "ObjectId de la localidad"
        piso:
          type: string
        departamento:
          type: string
        persona:
          type: string
          description: "ObjectId de la persona asociada"
      required:
        - calle
        - numero
        - localidad
        - persona
