#### getAll() Compra
GET http://localhost:3000/api/compras

### getOne() Compras
GET http://localhost:3000/api/compras/67b5fde6b00f16fc64739b48
###
POST http://localhost:3000/api/compras/
Content-Type: application/json

{
  "personaId": "67fd126aae7e20251fc7c6eb",
  
  "fecha_hora_compra": "17/8/2024-12:17",
  "items": [
    { "producto": "67fd1d3ff60099932c4f5bf3", "cantidad_producto": 2 }
    ],
 "calle":"Pte Roca",
 "numero":900,
 "localidadId":"67f0395b6779d65a745c26f0"
}


### update() Compras
PUT http://localhost:3000/api/compras/67ec452c54d8f0019e5f0171
Content-Type: application/json

{
 "direccion_entrega": "Zeballos 462",
  "producto": "66c0bddc34088bbf80791763",
  "persona": "66abffd636c84d1bcc465c81",
  "empleado":"66c0bd7434088bbf80791762",
  "cantidad_producto":700,
  "fecha_hora_compra":"17/8/2024-12:16"
  

}

### update() Compras parcial
PATCH  http://localhost:3000/api/compras/6c0bf00fb0f82c4ec06d25d
Content-Type: application/json

{
   "cantidad_producto":800,
  "fecha_hora_compra":"19/8/2024-12:16",
  

  
}

###GET

GET http://localhost:3000/api/compras/67fa5ca7f4d649dcd73ab40e

DELETE http://localhost:3000/api/compras/67a8bfafbe12abfb5c8db158

###GETCOMPRAPERSONA
GET http://localhost:3000/api/compras/persona/67f81c2a10f4444c79f48086

### update

PUT   http://localhost:3000/api/compras/67aa82aaa5d7f0cc58cd3826
Content-Type: application/json

{
   "direccion_entrega":"Laprida 900",
  "persona":"67a12692fa0044f148f9b1fe",
 "fecha_hora_compra":"2025/18/02",
 "total_compra":1200

  
}
###
PUT  http://localhost:3000/api/compras/stock/67e85af67899f5b4c52b6f49

###Remove

DELETE   http://localhost:3000/api/compras/6805164eb8abab8d7f97a3ee

###GetVentasByUser

GET http://localhost:3000/api/compras/ventas/67fd1d0cf60099932c4f5bf2