#### getAll() Compra
GET http://localhost:3000/api/compras

### getOne() Compras
GET http://localhost:3000/api/compras/67b5fde6b00f16fc64739b48

#### add() Compras
POST http://localhost:3000/api/compras/
Content-Type: application/json

{
  "direccion_entrega": "Zeballos 1281",
  "fecha_hora_compra": "17/8/2024-12:17",
  "persona": "67a12692fa0044f148f9b1fe",
  "items": [
 
    { "producto":"674471dbe02ee91fd1b5f44d", "cantidad_producto":2}
    
  ]
}

### update() Compras
PUT http://localhost:3000/api/compras/66d1e4513f46336da71a26a2
Content-Type: application/json

{
 "direccion_entrega": "Zeballos 462",
  "producto": "66c0bddc34088bbf80791763",
  "persona": "66abffd636c84d1bcc465c81",
  "empleado":"66c0bd7434088bbf80791762",
  "cantidad_producto":700,
  "fecha_hora_compra":"17/8/2024-12:16",
  

}

### update() Compras parcial
PATCH  http://localhost:3000/api/compras/6c0bf00fb0f82c4ec06d25d
Content-Type: application/json

{
   "cantidad_producto":800,
  "fecha_hora_compra":"19/8/2024-12:16",
  

  
}

###GET

GET http://localhost:3000/api/compras/67aa82aaa5d7f0cc58cd3826

DELETE http://localhost:3000/api/compras/67a8bfafbe12abfb5c8db158

###GETCOMPRAPERSONA
GET http://localhost:3000/api/compras/persona/67a12692fa0044f148f9b1fe

### update

PUT   http://localhost:3000/api/compras/67aa82aaa5d7f0cc58cd3826
Content-Type: application/json

{
   "direccion_entrega":"Laprida 900",
  "persona":"67a12692fa0044f148f9b1fe",
 "fecha_hora_compra":"2025/18/02",
 "total_compra":1200

  
}
###
PUT  http://localhost:3000/api/compras/stock/67b791d68c993b923f20fa7f

