
#### getAll() Empleados
GET http://localhost:3000/api/empleados

### getOne() Empleados
GET http://localhost:3000/api/empleados/66d1e4a43f46336da71a26a3

#### add() empleados
POST http://localhost:3000/api/empleados/
Content-Type: application/json

{
  "nombre": "Ruben",
  "apellido": "Di Martino",
  "telefono": "3465663412",
  "email": "ruben@200",
  "compras":[]
  
}

### update() empleados
PUT http://localhost:3000/api/empleados/66c0bd7434088bbf80791762
Content-Type: application/json

{
    "nombre": "Nacho",
  "apellido": "Di Martino",
  "telefono": "3465663410",
  "email": "nachojdimartino@gmail.com.ar",
  "compras":[]
  
 
}

###

DELETE http://localhost:3000/api/empleados/66d1e4a43f46336da71a26a3