### GET ALL 
GET http://localhost:3000/api/productos/

### GET ONE
GET http://localhost:3000/api/productos/674470dee02ee91fd1b5f449
### CREATE 
POST http://localhost:3000/api/productos/
Content-Type: application/json

{
  "descripcion": "zapatoo  amarillo",
  "precio": 500,
  "stock": 20,
  "categoria": "67365f0084281b88225d49a7",
  "persona": "674060e8f89e116e306c67d0"
}

### UPDATE
PATCH   http://localhost:3000/api/productos/674470dee02ee91fd1b5f449
Content-Type: application/json

{
 
 "stock":30

}

### REMOVE 
DELETE http://localhost:3000/api/productos/66c0bddc34088bbf80791763
