### GET ALL 
GET http://localhost:3000/api/productos/

### GET ONE
GET http://localhost:3000/api/productos/66c0bddc34088bbf80791763

### CREATE 
POST http://localhost:3000/api/productos/
Content-Type: application/json

{
  "descripcion": "Buzo ",
  "precio": 500,
  "stock": 20,
  "categoria": "67365f0084281b88225d49a7",
  "persona": "6706f21e81b79fdfc13a3200"
}

### UPDATE
PUT http://localhost:3000/api/productos/66fda8c28e6f95f4dbd168f6
Content-Type: application/json

{
  "descripcion": "Camisa",
  "precio": 401

}

### REMOVE 
DELETE http://localhost:3000/api/productos/66c0bddc34088bbf80791763
