### GET ALL 
GET http://localhost:3000/api/productos/

### GET ONE
GET http://localhost:3000/api/productos/66c0bddc34088bbf80791763

### CREATE 
POST http://localhost:3000/api/productos/
Content-Type: application/json

{
  "descripcion": "remera oversize",
  "precio": 400,
  "stock": 30,
  "categoria": "66a991e4f69972104ef25c7c",
  "persona": "66abffd636c84d1bcc465c81"
}

### UPDATE
PUT http://localhost:3000/api/productos/66fda8c28e6f95f4dbd168f6
Content-Type: application/json

{
  "descripcion": "Camisa",
  "precio": 401

}

### REMOVE 
DELETE http://localhost:3000/api/productos/66c0bddc34088bbf80791763
