## createDevolution

POST http://localhost:3000/api/devolucion/
Content-Type: application/json

{

    "itemId":"67fa8276363631fb55894109",

    "motivo":"Realizo la devolucion porque encuentro defectos",
    "cantidad_devuelta":2






}

###
PUT http://localhost:3000/api/devolucion/67ed2f8812ebae29c0d58e0d
Content-Type: application/json

{

"estado":"Aceptada"

}

### getByVendedor
GET http://localhost:3000/api/devolucion/67acbb331443b4bd7becf3b1

### getByVendedor
GET http://localhost:3000/api/devolucion/comprador/67acbb331443b4bd7becf3b1

###Actualiza solicitud
PATCH  http://localhost:3000/api/devolucion/67fafeb7310c509023a75f00
Content-Type: application/json

{
    
"estado":"Cerrada",
"fechaCierre":"14/04/2025",
"mensajeCierre":"El producto llego con exito a su destino"

}