## createDevolution

POST http://localhost:3000/api/devolucion/
Content-Type: application/json

{

    "itemId":"67e490e20abb8a3c72bf7f65",

    "motivo":"Realizo la devolucion porque encuentro defectos",
    "cantidad_devuelta":2






}

###
PUT http://localhost:3000/api/devolucion/67e1522f323f750865b11a64
Content-Type: application/json

{

"estado":"Aceptada"

}

### getByVendedor
GET http://localhost:3000/api/devolucion/67acbb331443b4bd7becf3b1

### getByVendedor
GET http://localhost:3000/api/devolucion/comprador/67a12692fa0044f148f9b1fe