### GET ALL 
GET http://localhost:3000/api/historico-precios/

### GET ONE
GET http://localhost:3000/api/historico-precios/66aa5c3a8b59051e68f40c4e

### CREATE 
POST http://localhost:3000/api/historico-precios/
Content-Type: application/json

{
  "valor": 20000,
  "fechaDesde": "10/9/2024",
  "producto": "66fda8c28e6f95f4dbd168f6"
}

### UPDATE
PUT http://localhost:3000/api/historico-precios/66aa5c3a8b59051e68f40c4e
Content-Type: application/json

{
  "valor": 301
}

### REMOVE 
DELETE http://localhost:3000/api/historico-precios/66a9987c052e5cf8f8f5d6c2
Content-Type: application/json

###GETHISTORICOPRODUCTO
GET http://localhost:3000/api/historico-precios/producto/66fda8c28e6f95f4dbd168f6
