#### getAll() Personas
GET http://localhost:3000/api/personas

### getOne() Personas
GET http://localhost:3000/api/personas/66abffd636c84d1bcc465c81

### Verificar rutas no definidas
GET http://localhost:3000/api/perssss


#### add() Personas
POST http://localhost:3000/api/personas/
Content-Type: application/json

{
  "nombre": "valen",
  "apellido": "bertone",
  "telefono": "3413112333333",
  "mail": "lotar_18@hotmail.com",
  "prods_publicados":[]
  
}

### update() Personas
PUT http://localhost:3000/api/personas/66abffd636c84d1bcc465c81
Content-Type: application/json

{
  "nombre": "juan",
  "apellido": "Lopez",
  "telefono": "111111",
  "mail": "carlopsssez@yahoo.com",
  "prods_publicados":["66ac015354ef7257fea422f8"]
}

### update() Personas parcial
PATCH  http://localhost:3000/api/personas/66a549ac6c4ca8c59081d29a
Content-Type: application/json

{
  "nombre": "Tony",
  "apellido": "Montana",
  "telefono": "777777",
  "mail": "tmontana@scarface.com"
}

###

DELETE http://localhost:3000/api/personas/66abf927b3608613b49c3c12