#### getAll() Personas
GET http://localhost:3000/api/personas

### getOne() Personas
GET http://localhost:3000/api/personas/67fd1d0cf60099932c4f5bf2

### getPersonaByMail
GET http://localhost:3000/api/personas/email/bertonev17@gmail.com

### Verificar rutas no definidas
GET http://localhost:3000/api/perssss


#### add() Personas
POST http://localhost:3000/api/personas/
Content-Type: application/json

{
  "nombre": "Juand",
  "apellido": "Di Martino",
  "telefono": "3413112333333",
  "mail": "Juand",
  "prods_publicados":[],
  "password": "123",
  "carrito":[],
  "rol":"Administrador"
  
  
  
 
}

### update() Personas
PUT http://localhost:3000/api/personas/680110a48c723f378365af93
Content-Type: application/json

{
  "nombre": "Valen",
  "apellido": "Bertone",
  "telefono": "2222",
  "mail": "bertonev17@gmail.com"
}

### update() Personas parcial
PATCH  http://localhost:3000/api/personas/67fd126aae7e20251fc7c6eb
Content-Type: application/json

{
  "direccion":"67fa79a4363631fb558940e90"
}
###""

DELETE http://localhost:3000/api/personas/66f3e74a4be92d4d11263d9a


###UpdatePassword

PATCH http://localhost:3000/api/personas/updatePassword
Content-Type: application/json

{
"mail":"nachojdimartino@gmail.com",
"passwordAnterior":"nacho",
"passwordNueva":"na"


}