### Add estado_seguimiento
POST http://localhost:3000/api/estado-seguimiento/
Content-Type: application/json

{
 
  "empleado":"67fbd07a9eae2eaab19696bb",
  "seguimiento":"67febb70621883bd7d6be6b1"



}

### BUSCA EMPLEADO estado_seguimiento
GET  http://localhost:3000/api/estado-seguimiento/67f039326779d65a745c26e


### BUSCA estados del empleado
GET  http://localhost:3000/api/estado-seguimiento/empleado/67feb66f3a7e0e2f251c3b22

### Add estado_seguimiento
PATCH  http://localhost:3000/api/estado-seguimiento/67f855de1c57979b51bda6a3

{
 
  "condicion":"Cerrado"
 


}