####
POST http://localhost:3000/api/correo/
Content-Type: application/json

{
  "origen":"bertonev17@gmail.com",
  "destinatario":"nachojdimartino@gmail.com",
  "asunto":"prueba",
  "mensaje":"Hola ma"
}